version: '3'

services:
  pharmacysystemapi:
    image: pharmacysystemapi
    build:
      context: ./PharmacySystemAPI
      dockerfile: Dockerfile
  database:
    image: "mongo:latest"
    ports:
    - "0.0.0.0:27017:27017"
