version: '3'

services:
  pharmacysystemapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "0.0.0.0:8080:80"
  database:
    image: "mongo:latest"
    ports:
    - "0.0.0.0:27017:27017"